feat: display CHEFS data in submissions table
bcgov/nr-permitting-navigator-service pull request #2
Opened 2023-11-30 00:40 UTC by wilwong89

# Description
Display CHEFS data in submissions table

Updated SubmissionsView.vue, formatters.ts
SubmissionsView retrieves CHEFS data only for currently displayed rows formatters.ts has a new shorter format function

## Types of changes

New feature (non-breaking change which adds functionality)

## Checklist

- [X] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] I have checked that unit tests pass locally with my changes
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

2023-11-30 22:57 UTC, kyle1morel requested changes
The approach is good with lazy loading the true submission data as needed, but the current implementation completely falls apart when you begin sorting. This will need to be addressed before merging. Recommend tracking the values coming back from the DataTable @page and @value-change emits. Use those values with the @update:sort-field and @update:sort-order callbacks to correctly get the current displayed rows to load in.

2023-12-02 01:54 UTC, kyle1morel approved these changes

2023-12-04 18:56 UTC, jujaga approved these changes

2023-12-04 19:05 UTC, TimCsaky commented on app/src/routes/v1/chefs.ts
> +  chefsController.getFormExport(req, res, next);
minor point: maybe at some point, consider calling this `submissionExport`.  form export is another chefs feature. i remember from working with chefs it was useful to differentiate between submissions and the form itself.

2023-12-04 19:06 UTC, TimCsaky commented on app/src/services/chefs.ts
> +      const response = await chefsAxios(formId).get(`forms/${formId}/export`, {
although the path itself uses form entity 🤷

2023-12-06 00:22 UTC, merged